version: '3.7'

services:
    tailwindcss:
        container_name: 'tailwindcss_container'
        build: .
        restart: unless-stopped
        ports:
            - '9000:9000'
        volumes:
            - './src:/var/www'
        working_dir: /var/www
        command: bash -c "npm install && npm run dev"

networks:
    default:
        external:
            name: my_docker_network

